GET https://render-test-s4lq.onrender.com/api/persons

###

GET https://render-test-s4lq.onrender.com/


###
GET https://render-test-s4lq.onrender.com/info

###
GET https://render-test-s4lq.onrender.com/api/persons/1